# Generated by Django 5.1.4 on 2024-12-18 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0024_buslocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="venueowner",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venueowner",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venueowner",
            name="timestamp",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
