# Generated by Django 5.1.4 on 2024-12-19 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0025_venueowner_latitude_venueowner_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venueowner",
            name="occupancy",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="venueowner",
            name="seats",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="venueowner",
            name="seats_available",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="venueowner",
            name="venue",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="owner.venue",
            ),
        ),
    ]
