# Generated by Django 5.1.4 on 2024-12-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0027_remove_venueowner_venue_alter_venueowner_occupancy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
